# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QPushButton, QLineEdit,
                             QInputDialog, QApplication,QMainWindow)
from datetime import datetime
from PyQt5.QtWidgets import QMessageBox

class OrderWindow(QMainWindow):

    order = []
    orderId =  0

    def margin(self):
        "Sets Margin Required"
        try:   
            qty = int(self.lineEdit_qty.text())
            ltp = float(self.label_ltp1.text())
            if self.radioButton_cnc.isChecked():
                if self.radioButton_market.isChecked():
                    margin = ltp*qty
                    self.label_margin.setText(str(margin))
                else:
                    lp = float(self.lineEdit_price.text())
                    margin = lp * qty
                    self.label_margin.setText(str(margin))
            else:
                if self.radioButton_market.isChecked():
                    margin = ltp*qty/10
                    self.label_margin.setText(str(margin))
                else:
                    lp = float(self.lineEdit_price.text())
                    margin = lp * qty
                    margin = margin/10
                    self.label_margin.setText(str(margin))
        except:
            qty = 1
            price = self.label_ltp1.text()
            margin = price*qty
            self.label_margin.setText(str(margin))

    def save_order(self):
        "This will save the order details in a list"
        orderdtl = {}
        status = True
        ordertype = ''
        tradeprice = ''
        stoploss = ''
        ltp = self.label_ltp1.text()
        bs = self.label_order.text()
        if self.radioButton_market.isChecked():
            ordertype = 'Market'
            tradeprice = ltp
        if self.radioButton_limit.isChecked():
            ordertype = 'Limit'
            tradeprice = self.lineEdit_price.text()
        if self.radioButton_sl.isChecked():
            ordertype = 'StopLoss'
            tradeprice = self.lineEdit_price.text()
            stoploss = self.lineEdit_tp.text()
            if bs == 'Buy':
                if float(stoploss) >= float(tradeprice):
                    self.messagebox('bsl')
                    status = False
            else:
                if float(stoploss) <= float(tradeprice):
                    self.messagebox('ssl')
                    status = False
        stock = self.label_stock.text()
        qty = self.lineEdit_qty.text()
        product = ''
        if self.radioButton_mis.isChecked():
            product = 'MIS'
        else:
            product = 'CNC'
        print(product)
        tradevalue = self.label_margin.text()
        time = datetime.now()
        print(time)
        if status == True:
            self.close()
            for x in range(9999999):
                OrderWindow.orderId = OrderWindow.orderId + 1
                print(OrderWindow.orderId)
                break
            orderdtl['orderId'] = OrderWindow.orderId
            print(orderdtl)
            orderdtl['time'] = time
            orderdtl['stock'] = stock
            orderdtl['qty'] = qty
            orderdtl['ltp'] = ltp
            orderdtl['bs'] = bs
            orderdtl['tradeprice'] = tradeprice
            orderdtl['tradevalue'] = tradevalue
            orderdtl['product'] = product
            orderdtl['ordertype'] = ordertype
            orderdtl['stoploss'] = stoploss
            OrderWindow.order.append(orderdtl)

    def limit(self):
        self.lineEdit_price.setEnabled(True)
        limitprice = self.label_ltp1.text()
        self.lineEdit_price.setText(limitprice)
        self.lineEdit_price.setValidator(QtGui.QIntValidator(1,99999))
        self.lineEdit_tp.clear()
        self.lineEdit_tp.setEnabled(False)
        self.margin()
        

    def sl(self):
        triggerprice = self.label_ltp1.text()
        self.lineEdit_tp.setEnabled(True)
        self.lineEdit_tp.setText(triggerprice)
        self.lineEdit_tp.setValidator(QtGui.QIntValidator(1,99999))
        self.lineEdit_price.setEnabled(True)
        self.lineEdit_price.setText(triggerprice)
        self.lineEdit_price.setValidator(QtGui.QIntValidator(1,99999))
        self.margin()

    def market(self):
        self.lineEdit_price.clear()
        self.lineEdit_tp.clear()
        self.lineEdit_price.setEnabled(False)
        self.lineEdit_tp.setEnabled(False)

    def messagebox(self,message):
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setText("Alert")
        if message == 'bsl':
            msg.setInformativeText("Stoploss must be lower than buying price")
        if message == 'ssl':
            msg.setInformativeText("Stoploss must be higher than selling price")
        msg.setWindowTitle("Alert")
        msg.setStandardButtons(QMessageBox.Ok)
        msg.show()
        msg.exec()

        
        


    
    def __init__(self):
        super().__init__()
        self.setObjectName("OrderWindow")
        self.resize(754, 510)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 9, 500, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_order = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_order.setFont(font)
        self.label_order.setText("")
        self.label_order.setObjectName("label_order")
        self.horizontalLayout.addWidget(self.label_order)
        self.label_stock = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_stock.setFont(font)
        self.label_stock.setText("")
        self.label_stock.setObjectName("label_stock")
        self.horizontalLayout.addWidget(self.label_stock)
        self.label_ltp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_order.setFont(font)
        self.label_order.setText("LTP")
        self.label_order.setObjectName("label_ltp")
        self.horizontalLayout.addWidget(self.label_ltp)
        self.label_ltp1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_order.setFont(font)
        self.label_order.setText("")
        self.label_order.setObjectName("label_ltp1")
        self.horizontalLayout.addWidget(self.label_ltp1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 321, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 140, 511, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.radioButton_mis = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_mis.setFont(font)
        self.radioButton_mis.setObjectName("radioButton_mis")
        self.horizontalLayout_3.addWidget(self.radioButton_mis)
        self.radioButton_cnc = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_cnc.setFont(font)
        self.radioButton_cnc.setObjectName("radioButton_cnc")
        self.horizontalLayout_3.addWidget(self.radioButton_cnc)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 200, 661, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_qty = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_qty.setFont(font)
        self.label_qty.setAlignment(QtCore.Qt.AlignCenter)
        self.label_qty.setObjectName("label_qty")
        self.verticalLayout_3.addWidget(self.label_qty)
        self.lineEdit_qty = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_qty.sizePolicy().hasHeightForWidth())
        self.lineEdit_qty.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_qty.setFont(font)
        self.lineEdit_qty.setObjectName("lineEdit_qty")
        self.lineEdit_qty.setValidator(QtGui.QIntValidator(1,9999999))
        self.verticalLayout_3.addWidget(self.lineEdit_qty)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_price = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_price.setFont(font)
        self.label_price.setAlignment(QtCore.Qt.AlignCenter)
        self.label_price.setObjectName("label_price")
        self.verticalLayout_2.addWidget(self.label_price)
        self.lineEdit_price = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_price.sizePolicy().hasHeightForWidth())
        self.lineEdit_price.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_price.setFont(font)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.verticalLayout_2.addWidget(self.lineEdit_price)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_tp = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_tp.setFont(font)
        self.label_tp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tp.setObjectName("label_tp")
        self.verticalLayout.addWidget(self.label_tp)
        self.lineEdit_tp = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tp.sizePolicy().hasHeightForWidth())
        self.lineEdit_tp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_tp.setFont(font)
        self.lineEdit_tp.setObjectName("lineEdit_tp")
        self.verticalLayout.addWidget(self.lineEdit_tp)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 320, 601, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_market = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_market.setFont(font)
        self.radioButton_market.setObjectName("radioButton_market")
        self.horizontalLayout_5.addWidget(self.radioButton_market)
        self.radioButton_limit = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_limit.setFont(font)
        self.radioButton_limit.setObjectName("radioButton_limit")
        self.horizontalLayout_5.addWidget(self.radioButton_limit)
        self.radioButton_sl = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_sl.setFont(font)
        self.radioButton_sl.setObjectName("radioButton_sl")
        self.horizontalLayout_5.addWidget(self.radioButton_sl)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 369, 711, 91))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_margin = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_margin.setFont(font)
        self.label_margin.setObjectName("label_margin")
        self.horizontalLayout_6.addWidget(self.label_margin)
        spacerItem1 = QtWidgets.QSpacerItem(190, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButton_bs = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.pushButton_bs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bs.sizePolicy().hasHeightForWidth())
        self.pushButton_bs.setSizePolicy(sizePolicy)
        self.pushButton_bs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_bs.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_bs.setFont(font)
        self.pushButton_bs.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_bs.setObjectName("pushButton_bs")
        self.pushButton_bs.clicked.connect(self.save_order)
        self.horizontalLayout_6.addWidget(self.pushButton_bs)
        self.pushButton_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_6.addWidget(self.pushButton_cancel)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(320, 280, 351, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_tperr = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_tperr.setFont(font)
        self.label_tperr.setText("")
        self.label_tperr.setObjectName("label_tperr")
        self.horizontalLayout_7.addWidget(self.label_tperr)
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.radioButton_cnc.setChecked(True)
        self.radioButton_market.setChecked(True)
        self.lineEdit_price.setEnabled(False)
        self.lineEdit_tp.setEnabled(False)
        self.lineEdit_qty.setText("1")

        #Signals
        self.lineEdit_qty.textChanged[str].connect(self.margin)
        self.lineEdit_price.textChanged[str].connect(self.margin)
        self.radioButton_mis.clicked.connect(self.margin)
        self.radioButton_cnc.clicked.connect(self.margin)
        self.pushButton_cancel.clicked.connect(self.close)
        self.radioButton_limit.clicked.connect(self.limit)
        self.radioButton_sl.clicked.connect(self.sl)
        self.radioButton_market.clicked.connect(self.market)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, OrderWindow):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("OrderWindow", "Order Window"))
        self.label_3.setText(_translate("OrderWindow", "Order Type: Regular"))
        self.radioButton_mis.setToolTip(_translate("OrderWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#000000;\">Margin Intraday SquareOff. Requires lower margin. Position needs to squared off before market closes.</span></p></body></html>"))
        self.radioButton_mis.setText(_translate("OrderWindow", "Intraday(MIS)"))
        self.radioButton_cnc.setToolTip(_translate("OrderWindow", "<html><head/><body><p><span style=\" font-style:italic;\">Longterm investment. Requires full upfront</span></p></body></html>"))
        self.radioButton_cnc.setText(_translate("OrderWindow", "Longterm(CNC)"))
        self.label_qty.setText(_translate("OrderWindow", "Qty"))
        self.label_price.setText(_translate("OrderWindow", "Price"))
        self.label_tp.setText(_translate("OrderWindow", "Trigger Price"))
        self.radioButton_market.setText(_translate("OrderWindow", "Market"))
        self.radioButton_limit.setText(_translate("OrderWindow", "Limit"))
        self.radioButton_sl.setText(_translate("OrderWindow", "SL"))
        self.label_7.setText(_translate("OrderWindow", "Margin required"))
        self.label_margin.setText(_translate("OrderWindow", "TextLabel"))
        self.pushButton_bs.setText(_translate("OrderWindow", "PushButton"))
        self.pushButton_cancel.setText(_translate("OrderWindow", "Cancel"))
        self.label_ltp.setText(_translate("OrderWindow", "LTP"))


